baseURL = "http://jasongan.xyz/"
#languageCode = "en-us"
title = "Jason Gan"
theme = "alpha-church"
themesDir = "./themes"
summaryLength = 10
rssLimit = 5
paginate = 8
disqusShortname = "jasongan.xyz"

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  series = "series"
  categories = "categories"


#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resource"
    weight = 3

  [[menu.main]]
    name = "Reward"
    parent = "Resource"
    url = "/reward"
    weight = 2

  [[menu.main]]
    name = "Rock coder"
    parent = "Resource"
    url = "/rock"
    weight = 1

  [[menu.main]]
    name = "Outline"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories"
    parent = "Outline"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Outline"
    weight = 2

  [[menu.main]]
    name = "Fork me"
    #identifier = "tags"
    url = "https://github.com/Gan-Jason/Gan-Blog"
    weight = 4

# Paramaters for the whole site
[params]
  toc = true                                                                          # 是否开启目录
  photoswipe = true
  title = "Welcome to Gan Gan's blog"
  subtitle = "很高兴认识你○( ＾皿＾)っHiahiahia…"
  author = "Jason Gan"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  talkyardServerUrl = "https://comments-for-www-jasongan-xyz.talkyard.net"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"
  customCSS = ["example.css"]

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true


  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "formspree"
    confirm_page = "/contact_thanks"
    formspree_email="binuogan@gmail.email"


    [params.footer]
      copyright = ["© 2017 - 2068 Jason Gan · 小栗旬-甘 版权所有",
                   "Designer: [Jason Gan](https://github.com/Gan-Jason)",
                   "沪ICP备10000000号-1"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "weibo"
      icon = "fa-weibo"
      icon_pack = "fab"
      link = "https://weibo.com/u/5585920563"

    [[params.links]]
      service = "zhihu"
      icon = "fa-zhihu"
      icon_pack = "fab"
      link = "https://www.zhihu.com/people/tang-seng-xi-fa-yong-bai-shi"

    [[params.links]]
      service = "gmail"
      icon = "fa-at"
      icon_pack = "fas"
      link = "mailto:binuogan@gmail.com"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
